### ISSUE TITLE
Importing an Image from IBM Cloud Object Storage section has changed.

### ISSUE THREAD

**Issue by bpersich** [IBM-Bluemix-Docs/image-templates#10]
In the section **Importing an Image from IBM Cloud Object Storage**, there is a difference between portal and console:
Control Portal: Devices>Device List>Images>*Import Image from IBM COS*
Console: Devices>Device List>Images>*Import Custom Images*

**Comment by William-Scott-Holmes** [comment]
So in this case we would want the UI's to be synced up to the first one mentioned ^^, since we don't really use the term "custom" all that much - correct?

**Comment by William-Scott-Holmes** [comment]
We are documenting the console method since portal will be deprecated.
