### ISSUE TITLE
Password match requirement

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/image-templates#2]
It's not documented apparently in your document.
I request you to add the description like below

When capturing an image
the actual system OS passwords do have to be matched with what we have on the password section of the portal

**Comment by mlgordon** [comment]
@khayama Thank you for this feedback. We will take a look into this and update the content accordingly.

**Comment by khayama** [comment]
Please let me know if it's reflected.

**Comment by khayama** [comment]
In all cases, the passwords for the OS and any add-ons such as R1soft must match those listed in Portal for each software item or automated deployment will fail due to a password mismatch.

**Comment by mlgordon** [comment]
@khayama The content has been updated per your request. You can see the addition as a "tip" following step three in this content section: https://console.bluemix.net/docs/infrastructure/image-templates/create-standard-image.html#creating-a-standard-image

**Comment by khayama** [comment]
Thanks! Looks great :)
No problem to close this issue.
