### ISSUE TITLE
What circumstances define whether a image is enabled for Cloud Init?

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Bluemix-Docs/image-templates#4]
Really pleased to see this topic included. 

The wording leaves me confused as to what circumstances I get a cloud-init enabled image. This sentence "_without selecting additional software, post-provisioning scripts, or advanced monitoring_." It is not clear to me from this whether in these cases I get a cloud-init enabled image or not?

**Comment by gudrun-wolfgram** [comment]
Hi @stevestrutt. Thanks for your feedback. I attempted to clarify the information with the following revision. 

_The following operating systems now default to a cloud-init enabled image when you order a virtual server without add-ons. (Add-ons include additional software, post-provisioning scripts, and advanced monitoring.)_

You do not get a cloud-init enabled image if you include add-ons (software, provisioning scripts, advanced monitoring).

**Comment by stevestrutt** [comment]
Thanks that is clearer
