### ISSUE TITLE
Change request - export image

### ISSUE THREAD

**Issue by gaskinner84** [IBM-Bluemix-Docs/image-templates#9]
Hello,

I notice that there is no stipulations to character limitations to the template name in: 

https://cloud.ibm.com/docs/infrastructure/image-templates?topic=image-templates-exporting-an-image-to-ibm-cloud-object-storage

Can we update this information to reflect: https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-getting-started

Specifically:  "Object keys can be up to 1024 characters in length, and it's best to avoid any characters that might be problematic in a web address. For example, ?, =, <, and other special characters might cause unwanted behavior if not URL-encoded."

We have many customers creating filenames with special characters, sending failed transactions to our backend teams. 

Regards,

Gary S.
ACS-Storage Support Engineer
IBM Cloud Support

**Comment by William-Scott-Holmes** [comment]
@gaskinner84, I've now updated the topic with the following tip:

"If you plan to export this image template to IBM Cloud Object Storage, make sure its name does not contain any characters that might be problematic in a web address. For example, ?, =, <, and other special characters might cause unwanted behavior if not URL-encoded."  Thanks!

**Comment by gaskinner84** [comment]
Thanks, William!
